# Generated by Django 2.2.9 on 2020-09-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
