# Generated by Django 2.2.9 on 2020-09-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='image',
        ),
    ]
