# Generated by Django 2.2.9 on 2020-08-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_place_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='info',
        ),
    ]
