# Generated by Django 2.2.9 on 2020-08-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_remove_place_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
