# Generated by Django 2.2.9 on 2020-09-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_place_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='distant',
            field=models.CharField(default='غير محدد', max_length=10),
        ),
    ]
