# Generated by Django 2.2.9 on 2020-09-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_place_distant'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='source',
            field=models.CharField(blank=True, default='www.tritlas.com', max_length=300, null=True),
        ),
    ]
