# Generated by Django 2.2.9 on 2020-09-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_place_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='source',
            field=models.CharField(blank=True, default='http://www.triitlas.com/', max_length=300, null=True),
        ),
    ]
