# Generated by Django 2.2.9 on 2020-09-01 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0004_place_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('depart_loc', models.CharField(max_length=25)),
                ('depart_time', models.CharField(max_length=6)),
                ('nights', models.IntegerField()),
                ('phone', models.CharField(max_length=18)),
                ('stay_place', models.CharField(max_length=20)),
                ('info', models.TextField()),
                ('contact', models.TextField()),
                ('price', models.IntegerField()),
                ('dist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city')),
            ],
        ),
    ]
