# Generated by Django 2.2.9 on 2020-09-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='boost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
