# Generated by Django 2.2.9 on 2020-09-03 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20200901_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_image ')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
    ]
