# Generated by Django 2.2.9 on 2020-09-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='post-image'),
        ),
    ]
