# Generated by Django 2.2.9 on 2020-09-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='contact',
            new_name='contact_and_reservation_info',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='depart_loc',
            new_name='depart_location',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='dist',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='info',
            new_name='information',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='stay_place',
            new_name='place_of_residence',
        ),
    ]
