# Generated by Django 2.2.9 on 2020-09-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_auto_20200922_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='ads',
            field=models.BooleanField(default=False),
        ),
    ]
