# Generated by Django 2.2.9 on 2020-09-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_trip_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='ads',
        ),
        migrations.CreateModel(
            name='tripAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_time', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('trip_ad', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
    ]
