# Generated by Django 2.2.9 on 2020-09-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=70)),
                ('category', models.CharField(choices=[('طلب إعلان مميز', 'طلب إعلان مميز'), ('اخر', 'أخر')], max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
