# Generated by Django 2.2.9 on 2020-09-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='الأسم',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='category',
            new_name='التصنيف',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='الرسالة',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='title',
            new_name='العنوان',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='phone',
            new_name='الهاتف',
        ),
    ]
