# Generated by Django 2.2.9 on 2020-09-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0003_auto_20200919_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='التصنيف',
            field=models.CharField(choices=[('طلب إعلان مميز', 'طلب إعلان مميز'), ('اخر', 'أخر'), ('أضف منتجع جديد', 'أضف منتجع جديد')], max_length=50),
        ),
    ]
