# Generated by Django 2.2.9 on 2020-09-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0004_auto_20200922_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='التصنيف',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='البريد_الإلكتروني',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='الرسالة',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='الأسم',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='الهاتف',
            new_name='phone',
        ),
    ]
