# Generated by Django 2.2.9 on 2020-09-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0005_auto_20200922_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
