# Generated by Django 2.2.9 on 2020-09-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0006_message_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ad',
        ),
    ]
